{% set name = "solvation_analysis" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 8dbf81b973e5e02c8dcd8e9247a794dd50bda701f4ce05fa681cd67e0bdb0ef8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.16.0
    - mdanalysis >=2.0.0
    - pandas
    - matplotlib-base
    - scipy

test:
  imports:
    - solvation_analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/solvation-analysis/
  summary: Rapidly understand solvation with MDAnalysis.
  description: |
    Solvation analysis implements a robust, cohesive, and fast set of
    methods for analyzing the solvation structure of a liquid. It seamlessly
    integrates with MDAnalysis, making use of the core AtomGroup and Universe
    data structures to parse solvation information. If you are interested in
    understanding the solvation structure of a liquid, this package is for you!
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orionarcher
    - hmacdope
