{% set name = "solvation_analysis" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffc557a526ba3984b7efc09087284c10307dce379a3c8ec24c131fa57087312a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - versioneer-518
  host:
    - python {{ python_min }}
    - pip
    - versioneer-518
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - mdanalysis >=2.7.0
    - rdkit
    - pytest
    - pandas >=2.2
    - matplotlib-base
    - scipy ==1.12.0
    - plotly
    - statsmodels

test:
  imports:
    - solvation_analysis
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/solvation-analysis/
  summary: 'Rapidly understand solvation with MDAnalysis.'
  description: |
    Solvation analysis implements a robust, cohesive, and fast set of
    methods for analyzing the solvation structure of a liquid. It seamlessly
    integrates with MDAnalysis, making use of the core AtomGroup and Universe
    data structures to parse solvation information. If you are interested in
    understanding the solvation structure of a liquid, this package is for you!
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orionarcher
    - hmacdope
