{% set name = "solvation_analysis" %}
{% set version = "0.3.3a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solvation-analysis-{{ version }}.tar.gz
  sha256: dfa30a6c4f874d0db4b625573db318071e62060df3e4acb8bd71da9ea9f62615

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - versioneer-518
  host:
    - python >=3.8
    - pip
    - versioneer-518
  run:
    - python >=3.8
    - numpy >=1.20.0
    - mdanalysis >=2.0.0
    - pytest
    - pandas
    - matplotlib-base
    - scipy
    - plotly
    - statsmodels
    - rdkit

test:
  imports:
    - solvation_analysis
  commands:
#    - pip install rdkit pytest pathlib
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/solvation-analysis/
  summary: 'Rapidly understand solvation with MDAnalysis.'
  description: |
    Solvation analysis implements a robust, cohesive, and fast set of
    methods for analyzing the solvation structure of a liquid. It seamlessly
    integrates with MDAnalysis, making use of the core AtomGroup and Universe
    data structures to parse solvation information. If you are interested in
    understanding the solvation structure of a liquid, this package is for you!
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orionarcher
    - hmacdope
